name: simple_deployment_pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        if: ${{ !contains(github.event.head_commit.message, '#skip') && github.event_name == 'push'}}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokedex-img-list" #Must be unique in Heroku
          heroku_email: "nanyang@kth.se"
          healthcheck: "https://pokedex-img-list.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit,author,took
          custom_payload: |
            {
              attachments: [{
                color: 'danger',
                text: `a new version deployed to https://pokedex-img-list.herokuapp.com (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} build took ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: success()
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure()
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ !contains(github.event.head_commit.message, '#skip') && github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch