name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        if: ${{ contains(github.event.head_commit.message, '#skip') }}
        run: echo "skip merging and tagging"